MyTeletouch/Controllers/AngularLoaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTeletouch.Controllers
{
    public class AngularLoaderController : BaseController
    {
        // Route: /{culture}/angular/usershippingaddress

        /// <summary>
        /// Load angularjs form, which user should to fill.
        /// Route: /{culture}/angular/usershippingaddress
        /// </summary>
        /// <returns></returns>
        public ActionResult ApplicationUserShippingAddressPageCtrl()
        {
            return View();
        }
    }
}

MyTeletouch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes" />
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link rel="stylesheet" href="@Url.Content("~/bower_components/angular-material/angular-material.css")" />

    <!-- https://design.google.com/icons/#ic_find_replace -->
    <!-- http://google.github.io/material-design-icons/#getting-icons -->
    <!-- http://demo.oxygenna.com/triangular -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <base href="/">

       

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Myteletouch.com", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Shipping Adress", "ApplicationUserShippingAddressPageCtrl", "AngularLoader")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <!-- Angular Material -->
    <script src="../bower_components/angular-animate/angular-animate.js" type="text/javascript"></script>
    <script src="../bower_components/angular-aria/angular-aria.js" type="text/javascript"></script>
    <script src="../bower_components/angular-material/angular-material.js" type="text/javascript"></script>

    <!-- Angular Material -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>